### PR TITLE
Yo 14

### PR DESCRIPTION
**Pull request by joe-yeager**
The user can now request to have an activation email resent to them.

Edit:  This still needs more testing.  I refactored quite a bit and added a lockout timer, so that this cannot be utilized for spamming, either malicious or from impatient people.

Edit: This is done now, review away.

### CODE REVIEW

**Comment by ianaldrighetti** [comment]
Would it be difficult to add a maximum request interval? That way people can't hit the resend button over and over again because they're impatient?

**Comment by ladinu** [comment]
:+1:

**Comment by joe-yeager** [comment]
@ladinu Did you peer review this on the airplane? haha

**Comment by bbuxell** [comment]
Looks good. I tested out a few users emails, both activated and not activated and all of them responded correctly except `bNye@froyo.com` which gave me a 404.  Not sure why that one wouldn't be working since it's in the database.

**Comment by joe-yeager** [comment]
I should probably better define the 404 for this route, right now it throws a 404 if **any** of the data is not found, and bNye@froyo.com is one that I made in an integration test by bypassing the user service for one reason or another. So it does not have any data in the activation table, which is why it gets a 404.

Edit: Actually on second thought, I feel like this is an acceptable behavior.

**Comment by bbuxell** [comment]
Yeah, that makes sense.  I figured it was because of something like that. I agree that's acceptable, since it was a test case.  Not something that would happen with a real user.
#peer

**Comment by joe-yeager** [comment]
I'm going to hold off on merging this until https://github.com/FroYoInc/wafflecone/pull/33 gets merged.  Not fair for a 16 line pull request to deal with all the merge conflicts this will create.

**Comment by bbuxell** [comment]
I appreciate that.

**Pull request merged**
