### PR TITLE
Yo carpool service

### PR DESCRIPTION
**Pull request by ladinu**
# Description
- Improved method `addUserToCarpool()` by fixing a race condition issue where a non existant user would have been added to a carpool. 
- Updated `User` model to include `carpools` field where it would list all the `Carpool` the user is a participant of
- Added `getUserCarpools()` method to `carpool.svc` which retrieve the list of carpools a user is a participant of

### CODE REVIEW

**Comment by bbuxell** [comment]
what were the bugs you fixed?

**Comment by ladinu** [comment]
@bbuxell: There was a race condition in the first version where a non existent user would have been added to the carpool. I just modified the method to do it all in 1 query so the race condition could not happen.

**Comment by bbuxell** [comment]
looks good. we could maybe take out the `expectTrue()` and `expectFalse()` methods in the carpool service test, as the false one is only used once and true is never used at all, but that's not a deal breaker.
#peer

**Comment by ianaldrighetti** [comment]
#peer

**Pull request merged**
