### PR TITLE
Install Instructions

### PR DESCRIPTION
**Pull request by ianaldrighetti**
This PR is just the installation instructions, which include the front and back end portion.

### CODE REVIEW

**Comment by bbuxell** [comment]
this looks like the yo-25 story. you might have pulled from that before you added the install instructions

**Comment by ianaldrighetti** [comment]
@bbuxell Ah, crap. I switched to develop, but I think I may have brought them over :/

Any way I can get them out?

**Comment by bbuxell** [comment]
yo-25 is close to being done, we could just merge that one first, then you wouldn't really have an issue

**Comment by ianaldrighetti** [comment]
Okay, cool.

**Comment by ladinu** [comment]
#peer
If you could add the activation config to instructions that would be awesome!

**Comment by ianaldrighetti** [comment]
@ladinu Yup, just added a note in there to change it, it's on the same point as the baseurl as well :+1:

**Comment by ianaldrighetti** [comment]
NOTE TO SELF: Need to add `gulp integrate` to instructions so the database is setup. Woops.

**Comment by ladinu** [comment]
You don't have to run `gulp integrate`. If the DB does not exist, when wafflecone is run for the first time it will create the tables automatically

**Comment by ianaldrighetti** [comment]
Note to self: Need to mention changing the Google Maps API key in app.ts (if I didn't already) AND in the index.html as well.

**Comment by joe-yeager** [comment]
Looks good.  Good job!  #peer

**Pull request merged**
