### PR TITLE
Query Metrics

### PR DESCRIPTION
**Pull request by ladinu**
# Description

While working on yo-43, I had a quick idea to implement metric gathering in our rethinkdb queries. In the `Query` util, it now collect query execution time and send that information to a collection server over UDP.

Since it is sending this data over UDP, there is nothing you have to setup on your local machine. Development will not be impacted in anyways.

I modified `Query.run` method to accept a second parameter which you will have to provide if you want metric info for the query you are running. I added this parameter in `services/` where we were using `Query`.

You can view the graphs over [here](http://107.170.251.172/#/dashboard/db/default). If this get merged into develop, when you guys use develop for testing it will populate the dashboards and we will have more data.

### CODE REVIEW

**Comment by ianaldrighetti** [comment]
That's pretty cool. can this be disabled, though?

**Comment by ladinu** [comment]
What do you mean by disabled?

**Comment by ianaldrighetti** [comment]
So even once our sponsors install the app, will metrics be sent still?

**Comment by ladinu** [comment]
Yeah it can be disabled. We will just have to set `statsd.host`to something else like `localhost` and metrics won't get sent.

**Comment by ianaldrighetti** [comment]
Ah, okay. 

#peer

**Comment by joe-yeager** [comment]
Cool idea.  I think it should be opt-in rather than opt-out though, but that is something we could do in the install instructions.  #peer

**Pull request merged**
